apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-teams-tm
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vg-teams-tm
    spec:
      containers:
        - name: vg-teams-tm
          image: gcr.io/vg-teams/vg-teams-tm:298a654e305eb945472163fec136ac597dd6af2b
          # image: busybox:1.29.0
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
          envFrom:
          - secretRef:
              name: vg-teams-tm-prod-env
          ports:
            - containerPort: 8285
  selector:
    matchLabels:
      app: vg-teams-tm
