apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-teams-be
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: vg-teams-be
    spec:
      containers:
        - name: vg-teams-be
          image: gcr.io/vg-teams/vg-teams-be:d65df78dcb308032156eae32b5b9c78699b102d6
          # image: busybox:1.29.0
          resources:
            requests:
              cpu: 0.1
              memory: 512Mi
          envFrom:
          - secretRef:
              name: vg-teams-be-prod-env
          ports:
            - containerPort: 8284
  selector:
    matchLabels:
      app: vg-teams-be
